[package]
authors = [ "OLSF" ]
default-run = "carpe"
description = "a light miner for the 0L protocol"
edition = "2021"
license = "MIT"
name = "carpe"
repository = "https://github.com/OLSF/carpe"
version = "0.5.0"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }
built = { version = "0.5.1", features = ["git2"] }

[dependencies]
built = "0.5.1"
tauri = { version = "1.0.0-beta.8", features = ["api-all", "updater"] }
serde = { version = "1.0", features = [ "serde_derive" ] }
serde_json = "1.0"
url = { version = "^2.1", features = [ "serde" ] }
ol = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-wallet = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-types = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-client = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
tower = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
onboard = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-crypto = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-config = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-sdk = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
cli = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
txs = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
#ol-types = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
ol-types = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}

ol-keys = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}
diem-json-rpc-types = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}

resource-viewer = { git = "https://github.com/OLSF/libra.git", branch = "carpe-build"}

sysinfo = "0.16.4"
ctrlc = { version = "3.1.6", default-features = false }
dirs = "4.0.0"
keyring = "0.10.1"
anyhow = "1.0.38"
hex = "0.4.3"
tokio = { version = "1.3.0", features = ["full"] }
reqwest = "0.11.6"
glob = "0.3.0"
futures = "^0.3"
rand = "^0.8"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
simplelog = { version = "^0.11.0", features = ["paris"] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
default = [ "custom-protocol" ]

