[package]
authors = [ "OLSF" ]
default-run = "app"
description = "a light miner for the 0L protocol"
edition = "2018"
license = "MIT"
name = "app"
repository = "https://github.com/OLSF/carpe"
version = "0.1.0"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
serde = { version = "1.0", features = [ "serde_derive" ] }
serde_json = "1.0"
url = { version = "^2.1", features = [ "serde" ] }
ol = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
diem-wallet = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
diem-types = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
miner = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
onboard = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
diem-crypto = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
diem-config = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
txs = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
ol-types = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
ol-keys = { git = "https://github.com/olsf/libra.git", branch = "tauri"}
sysinfo = "0.16.4"
ctrlc = { version = "3.1.6", default-features = false }
dirs = "4.0.0"
anyhow = "1.0.38"
aes-gcm = "0.8.0"


[features]
custom-protocol = [ "tauri/custom-protocol" ]
default = [ "custom-protocol" ]
