[package]
authors = ["0LNetworkCommunity"]
default-run = "carpe"
description = "a light miner and wallet for libra"
edition = "2021"
license = "MIT"
name = "carpe"
repository = "https://github.com/0LNetworkCommunity/carpe"
version = "0.5.0"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }
built = { version = "0.5.1", features = ["git2"] }

[dependencies]

libra-query = { git = "https://github.com/0o-de-lally/libra-v7.git", branch = "genesis-econ" }
libra-tower = { git = "https://github.com/0o-de-lally/libra-v7.git", branch = "genesis-econ" }
libra-types = { git = "https://github.com/0o-de-lally/libra-v7.git", branch = "genesis-econ" }
libra-txs = { git = "https://github.com/0o-de-lally/libra-v7.git", branch = "genesis-econ" }
libra-wallet = { git = "https://github.com/0o-de-lally/libra-v7.git", branch = "genesis-econ" }

anyhow = "1.0.38"
futures = "0.3.24"
glob = "0.3.0"
hex = "0.4.3"
keyring = "0.10.1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
simplelog = { version = "^0.11.0", features = ["paris"] }
tauri = { version = "1.2.4", features = ["api-all", "updater"] }
tokio = "*"
url = { version = "^2.1", features = ["serde"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[dev-dependencies]
serde_yaml = "*"
