[package]
authors = ["you"]
default-run = "app"
description = "A Tauri App"
edition = "2018"
license = "GPL-3.0 License"
name = "app"
repository = "https://github.com/jbarszczewski/tauri-svelte-template"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.0.0-beta-rc.1"}

[dependencies]
tauri = {version = "1.0.0-beta.4", features =["api-all"]}
serde = {version = "1.0", features = ["serde_derive"]}
serde_json = "1.0"
url = {version = "^2.1", features = ["serde"]}
ol = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
libra-wallet = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
libra-types = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
miner = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
onboard = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
libra-swarm = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
libra-node = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
libra-config = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
txs = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
ol-types = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
ol-keys = {git="https://github.com/olsf/libra.git", branch="tauri-demo"}
sysinfo = "0.16.4"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
