[package]
name = "carpe"
version = "1.0.0"
authors = ["0LNetworkCommunity"]
default-run = "carpe"
description = "a light miner and wallet for libra"
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/0LNetworkCommunity/carpe"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }
built = { version = "0.5.1", features = ["git2"] }

[dependencies]
libra-query = { git = "https://github.com/0LNetworkCommunity/libra-framework.git", branch = "carpe-patches" }
libra-tower = { git = "https://github.com/0LNetworkCommunity/libra-framework", branch = "carpe-patches" }
libra-types = { git = "https://github.com/0LNetworkCommunity/libra-framework", branch = "carpe-patches" }
libra-txs = { git = "https://github.com/0LNetworkCommunity/libra-framework", branch = "carpe-patches" }
libra-wallet = { git = "https://github.com/0LNetworkCommunity/libra-framework", branch = "carpe-patches" }

# shared with libra-framework and diem
# anyhow = "1.0.38"
anyhow = "1.0.62"
futures = "= 0.3.24"
glob = "0.3.0"
hex = { version = "0.4.3", features = ["serde"] }
# once_cell = "1.18.0"
once_cell = "1.10.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
# log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
log = "0.4.17"
tokio = { version = "1.21.0", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

# only in carpe
directories = "5.0.1"
keyring = "0.10.1"
simplelog = { version = "^0.11.0", features = ["paris"] }
tauri = { version = "1.2.4", features = ["api-all", "updater", "devtools"] }


[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
carpe-canary = [] # for building canary versions which use separate config dirs.

[dev-dependencies]
serde_yaml = "0.8.24"
