# language: rust
# rust:
#   - stable
os: osx
osx_image: xcode7.3

  jobs:
    include:

      - language: rust
        rust:
          - stable
        jobs:
          allow_failures:
            - rust: nightly
          fast_finish: true
      - language: node.js
        node_js: "12.0"
        before_script:
          - cd angular-application
        script:
          - npm install
          - ng build --prod

node_js:
  - node


env:
  - RUST_BACKTRACE=1

# addons:
#   apt:
#     packages:
#       - libwebkit2gtk-4.0-dev
#       - libglib2.0-*
#       - libssl-dev
#       - libgtk-3-dev
#       - libappindicator3-dev
#       - patchelf
#       - librsvg2-dev
#       - libvips-dev

# install:
#   - if [ $TRAVIS_OS_NAME = windows ]; then choco install -y visualstudio2019buildtools --package-parameters "--productId visualstudio2019community --allWorkloads --includeRecommended --includeOptional --passive --locale en-US" rust; fi

# jobs:
#  include:
#    - language: rust
#      rust: stable

# env:
#   - NODE_VERSION="0.16"

# before_install:
#   - nvm install $NODE_VERSION

script:
  - yarn install --frozen-lockfile
  - yarn run tauri build
  
