language: node_js
node_js:
  - node
os:
  - windows
  - osx
  - linux

env:
  - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libwebkit2gtk-4.0-dev
      - libglib2.0-*
      - libssl-dev
      - libgtk-3-dev
      - libappindicator3-dev
      - patchelf
      - librsvg2-dev
      - libvips-dev

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install -y rust; else curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh; fi

script:
  - yarn install --frozen-lockfile
  - yarn run tauri build
  
