[workspace]
node_home = "/Users/lucas/code/rust/tauri-demo"
block_dir = "blocks"
db_path = "/Users/lucas/.0L/db"

[profile]
account = "01CAC9E962960658EC1E1F4616401188"
auth_key = "bd747fed786b7b8e68be54bef5ab44d801cac9e962960658ec1e1f4616401188"
statement = "Test"
ip = "1.1.1.1"
default_node = "http://localhost:8080/"
upstream_nodes = ["http://167.172.248.37:3030/"]

[chain_info]
chain_id = "experimental"
base_epoch = 241
base_waypoint = "81474141:fb7e5ff659a79667b6675f10954f46c4979a328685db8157cdc9c7a380e11ad1"
[tx_configs.baseline_cost]
max_gas_unit_for_tx = 10000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.critical_txs_cost]
max_gas_unit_for_tx = 1000000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.management_txs_cost]
max_gas_unit_for_tx = 100000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.miner_txs_cost]
max_gas_unit_for_tx = 10000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.cheap_txs_cost]
max_gas_unit_for_tx = 1000
coin_price_per_unit = 1
user_tx_timeout = 5000
