[workspace]
node_home = "/Users/lucas/code/rust/tauri-demo"
block_dir = "blocks"
db_path = "/Users/lucas/.0L/db"

[profile]
account = "9241971CDBE0286286489ADBF4E9D106"
auth_key = "1e10366a480b350ce051becbec29ab529241971cdbe0286286489adbf4e9d106"
statement = "Test"
ip = "1.1.1.1"
default_node = "http://localhost:8080/"
upstream_nodes = ["http://localhost:8080/"]

[chain_info]
chain_id = "experimental"
base_epoch = 0
base_waypoint = "0:683185844ef67e5c8eeaa158e635de2a4c574ce7bbb7f41f787d38db2d623ae2"
[tx_configs.baseline_cost]
max_gas_unit_for_tx = 10000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.critical_txs_cost]
max_gas_unit_for_tx = 1000000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.management_txs_cost]
max_gas_unit_for_tx = 100000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.miner_txs_cost]
max_gas_unit_for_tx = 10000
coin_price_per_unit = 1
user_tx_timeout = 5000

[tx_configs.cheap_txs_cost]
max_gas_unit_for_tx = 1000
coin_price_per_unit = 1
user_tx_timeout = 5000
