export const routes = {
  home: '/',
  wallet: '/wallet',
  accountDetails: '/account-details',
  addAccount: '/add-account',
  addWatchAccount: '/add-wathc-account',
  accountFromMnem: '/account-from-mnem',
  keygen: '/keygen',
  miner: '/miner',
  transfer: '/transfer',
  events: '/events',
  settings: '/settings',
  about: '/about',
  developer: '/dev',
  swarm: '/swarm',
  makeWhole: '/make-whole',
  txHub: '/transactions',
}
