name: Build app for OSs

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for #${{ matrix.os }}
    runs-on: ubuntu-latest #${{ matrix.os }}
#    strategy:
#      matrix:
#        include:
#          - os: ubuntu-latest
#            artifact_name: carpe
#            asset_name: carpe-linux-amd64
#          - os: windows-latest
#            artifact_name: carpe.exe
#            asset_name: carpe-windows-amd64
#          - os: macos-latest
#            artifact_name: carpe
#            asset_name: carpe-macos-amd64

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - uses: actions/checkout@v1
      - name: yarn info
        run: sudo apt update & sudo apt install libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev -y
      - name: yarn info
        run: yarn install --modules-folder ./node_modules
      - name: Build
        run: yarn run tauri build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
