name: gmp-compile

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        # - os: ubuntu-20.04
        #   vcpkg_triplet: x64-linux-release
        - os: macos-11
          vcpkg_triplet: x64-osx-dynamic
        - os: windows-2019
          vcpkg_triplet: x64-windows-release
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: osx deps
        if: ${{ matrix.config.os }} == macos-11
        run: brew install autoconf automake libtool

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: gmp
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.os }} == macos-11
        with:
          name: gmp-compile
          path: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.os }} == windows-2019
        with:
          name: gmp-compile
          path: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}

      - name: release win
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.config.os }} == windows-2019
        with:
          tag_name: gmp-libraries-${{ matrix.config.os }}
          body: "gmp libs built from source"
          files: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}

      - name: release osx
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.config.os }} == windows-2019
        with:
          tag_name: gmp-libraries-${{ matrix.config.os }}
          body: "gmp libs built from source"
          files: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}