name: gmp-compile

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        # - os: ubuntu-20.04
        #   vcpkg_triplet: x64-linux-release
        - os: macos-11
          vcpkg_triplet: x64-osx-release
        - os: windows-2019
          vcpkg_triplet: x64-windows-release
    steps:
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: gmp
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}

      - uses: actions/upload-artifact@v3
        with:
          name: gmp-compile
          path: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: gmp-libraries-${{ matrix.config.os }}
          files: ${{ github.workspace }}\vcpkg\installed\${{ matrix.config.vcpkg_triplet }}/**/*gmp*