name: lint

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:

      # Setup Node.js
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # checkout
      - name: checkout source
        uses: actions/checkout@v3

########  Lint  ########

      - name: yarn installation
        run: yarn install
      - name: lint TS
        run: yarn lint