name: lint

on:
  push:
    branches: ['*']

  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'release**'
      - 'canary**'
      - 'main'
  schedule:
    - cron: '0 5 * * *'  # Runs at 5am UTC / 1am ET daily
jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:
      # Setup Node.js
      - name: setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      # checkout
      - name: checkout source
        uses: actions/checkout@v4.1.1

      - name: yarn installation
        run: yarn install

      - name: lint TS
        run: yarn lint

  rust-lint:
    runs-on: macos-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: 1.84.1
          override: true

      - name: install rustfmt clippy
        shell: bash
        run: rustup component add rustfmt clippy

      - name: cache rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'libra' # to share across CI builds, so it is not job-id specific
          cache-on-failure: true

      - name: check format
        working-directory: ./src-tauri
        run: cargo fmt --all -- --check

      - name: lint
        working-directory: ./src-tauri
        run: cargo clippy --workspace --tests -- -D warnings
