name: lint

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'release**'
      - 'main'
jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:

      # Setup Node.js
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # checkout
      - name: checkout source
        uses: actions/checkout@v3

########  Lint  ########

      - name: yarn installation
        run: yarn install
      - name: lint TS
        run: yarn lint

  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --tests -- -D warnings