name: carpe-release-mac-x86

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+'

    branches:
      - 'canary*'
      - 'release-[0-9]+.[0-9]+.[0-9]+'
      - 'ci'
env:
  TAURI_PRIVATE_KEY: "dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5UmJEV1cwNHlkUm8rNnFkei9tRlBUaTdoWlRYT0EzWEZVYXE3SHRvNzBSQUFBQkFBQUFBQUFBQUFBQUlBQUFBQWZsNU9Gb0VLeFBCVEJrRkcrbjNaNklCTElxZ1d2V1BDcHZvWVNDbzd6YXNUa09MZmp1VzJ2bDRHbXR0NTdGM2luZWlsc08wL1B6eERGU1JwMHRTU3BNdDU1UStnTWR2MmU5NElVQWFCUFhPTExycE5maUh1NGRUQjBUdHV0TjJyejZHQjVKd3dIRFE9Cg=="
  TAURI_KEY_PASSWORD: "testonly"
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      ### DO NOT REMOVE: uncomment if you need to debug runner ###
      # - name: setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true

      # Setup Rust
      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: rustfmt

      # Setup Node.js
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # checkout
      - name: checkout source
        uses: actions/checkout@v3

########  CACHE  ########

      - uses: Swatinem/rust-cache@v2
        with:
           workspaces: ./src-tauri
           shared-key: ${{ matrix.os }}
           cache-all-crates: true

########  BUILD  ########

      - name: yarn installation
        run: yarn install

      # - name: pre-build rust
      #   working-directory: ./src-tauri
      #   run: cargo b --release

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{secrets.TAURI_PRIVATE_KEY}}
          TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}
        with:
          args: ${{contains(github.ref, 'canary') && '--config src-tauri/tauri.conf.canary.json --features carpe-canary' || '' }}
          # pass the rust feature flags for canary if the tag includes "canary"
          tagName: ${{contains(github.ref, 'canary') && 'v__VERSION__-canary' ||  'v__VERSION__' }}
          # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: ${{contains(github.ref, 'canary') && 'v__VERSION__-canary' ||  'v__VERSION__' }}
          releaseBody: '[draft]'
          releaseDraft: true
          prerelease: false
