name: carpe release

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      # Setup Rust
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt

      # Setup Node.js
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

########  UBUNTU  ########
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-20.04'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev
          version: 1.0
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev -y

########  WIN  ########

      - name: install dependencies (windows only)
        if: matrix.os == 'windows-latest'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH
        if: matrix.os == 'windows-latest'
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: vcpkg build
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: gmp
          triplet: x64-windows-release
          token: ${{ github.token }}

      - uses: actions/checkout@v3

########  CACHE  ########

      - uses: Swatinem/rust-cache@v2
        with:
          # The cargo workspaces and target directory configuration.
          # These entries are separated by newlines and have the form
          # `$workspace -> $target`. The `$target` part is treated as a directory
          # relative to the `$workspace` and defaults to "target" if not explicitly given.
          # default: ". -> target"
           workspaces: ./src-tauri
           shared-key: "libra" # to share across CI builds, so it is not job-id specific
           cache-all-crates: true

########  BUILD  ########

      - name: yarn installation
        run: yarn install

      - name: pre-build rust
        working-directory: ./src-tauri
        run: cargo b --release

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TAURI_PRIVATE_KEY: ${{secrets.TAURI_PRIVATE_KEY}}
          # TAURI_KEY_PASSWORD: ${{secrets.TAURI_KEY_PASSWORD}}

          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5N1FKS0ZZM1BwL25GaFdKU0tpNW5XREQyZnZjQTdkVWZSYUZWV0U5YThIUUFBQkFBQUFBQUFBQUFBQUlBQUFBQVp5dlhYNTlMa0c1OHMxK2hxWXNJWHc2VXVRZnRPUVR3TjloZTJTdXIrQnV2aXFSbTczWjNkdTlOU214YXhnVXA3SmNQQ3VzemlMV2ZKTWVNZTA0SWRraHU0VFJGbXI3UXpsTkREditxV1hFWUQ2MlVZam5lSDJ2OFA1Z05hZnY0U21mOWZxZ0JnZUk9Cg==
          TAURI_KEY_PASSWORD: 123456
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Carpe v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false