name: Build Binaries for Mac

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build Binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            artifact_name: carpe
            dir: dmg
            asset_name: carpe-macos-11
          # - os: macos-11
          #   artifact_name: carpe
          #   dir: dmg
          #   asset_name: carpe-macos-11
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - uses: actions/checkout@v1
      - name: yarn installation
        run: yarn install
      - name: Build Tauri
        run: RUST_BACKTRACE=1 yarn run tauri build
      - name: Rename binary
        run: mv src-tauri/target/release/bundle/${{ matrix.dir }}/*.${{ matrix.dir}} src-tauri/target/release/bundle/${{ matrix.dir }}/${{matrix.asset_name}}.${{matrix.dir}}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/${{ matrix.dir }}/*.${{ matrix.dir}}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload Updater Builds
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/macos/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
