name: Build Binaries for OSs

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Build Binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: carpe
            asset_name: carpe-linux-amd64
            dir: deb

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - uses: actions/checkout@v1
      - name: Ubuntu dependency
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev -y

      - name: yarn info
        run: yarn install
      - name: Build
        run: RUST_BACKTRACE=1 yarn run tauri build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/${{ matrix.dir }}/*.${{ matrix.dir}}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload for ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/appimage/*.AppImage
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true